name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-24.04  # 显式指定新版系统
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 显式覆盖隐式依赖
    - name: Force upload-artifact@v4
      uses: actions/upload-artifact@v4  # 强制声明新版

    - name: Configure Pages
      uses: actions/configure-pages@v4

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
